### ISSUE TITLE
Card on/off information

### ISSUE THREAD

**Issue by gabrielstuff** [ulfalfa/rfid-chafon#1]
Hi !
This is a great looking library.
I was wondering if you had implemented a card on/off functionnality.

When using PC/SC reader like ARC122U we easily get access to the on/off feature.

I guess we could poll and open close the device, but it looks kind of dumb.

Thanks,

G

**Comment by ulfalfa** [comment]
Hi,

thanks! Indeed I never heard of card on/off and I haven't seen such a functionality in the original client serial datastream.  If you mean, that something like an event is send, when the card enters, than it's something I also have not seen. The original client is pulling on a regular basis.

Cheers,
Ulf
