### ISSUE TITLE
compatible rfid-reader 

### ISSUE THREAD

**Issue by philippschwemberger** [ulfalfa/rfid-chafon#2]
Hi Ulf.

Thanks for this library. 
I try to make it work with this RFID-reader.

![20170828_121523](https://user-images.githubusercontent.com/25133178/29769682-ac7155e0-8beb-11e7-971b-f85305b35faf.jpg)

https://www.amazon.co.uk/Neuftech-Reader-125KHZ-EM4100-Contactless/dp/B018OYOR3E/ref=sr_1_3?ie=UTF8&qid=1502462938&sr=8-3&keywords=rfid+reader

Could you tell me which reader you used for this project?

Thank you very much!
Philipp

**Comment by ulfalfa** [comment]
Hi,

thanks. But unfortunatly my reader (Chafon 125kHz USB-Desktop Contactless Smart EM Karte RFID Reader/ Writer/ opierer/Duplizierer(T5557 / EM4305 / 4200) für Access Control + 5pcs Druckk) bought with amazon in 2015 is not listed anymore.
Looking at the description of your reader, it seems, that it's using a keyboard emulation - so it's only a reader that is emulating a keyboard. No writing....

Sorry for this...
Regards,
Ulf

**Comment by philippschwemberger** [comment]
No worries. Thank you very much for your quick response!
